import { readFileSync, writeFileSync } from "node:fs";

import type { Job } from "../src/types";

type JobPayload = {
  generatedAt: string;
  note: string;
  careerSignalCoverage: unknown;
  sources: unknown;
  jobs: Job[];
};

const publicPayloadNote =
  "Official-site normalized job payload. Full official descriptions are not republished; records keep short generated summaries, source links, salary signals, and matching metadata. Official sites remain the source of truth.";

function main() {
  const payload = JSON.parse(readFileSync("data/jobs.normalized.json", "utf8")) as JobPayload;
  const redactedPayload: JobPayload = {
    ...payload,
    note: publicPayloadNote,
    jobs: payload.jobs.map(redactJobForPublication),
  };

  writeFileSync("data/jobs.normalized.json", `${JSON.stringify(redactedPayload, null, 2)}\n`, "utf8");
  writeFileSync("data/jobs.seed.json", `${JSON.stringify(redactedPayload, null, 2)}\n`, "utf8");
  writeFileSync("src/data/jobs.generated.ts", renderGeneratedModule(redactedPayload), "utf8");
  console.log(`Redacted ${redactedPayload.jobs.length} jobs for public publication.`);
}

function redactJobForPublication(job: Job): Job {
  const abilitySignals = Array.from(new Set([...(job.abilitySignals ?? []), ...job.requirements.map(cleanText).filter(Boolean)])).slice(0, 6);
  const requirements = abilitySignals.length ? abilitySignals.slice(0, 5) : [job.category, job.direction].map(cleanText).filter(Boolean).slice(0, 5);
  const summaryParts = [
    `${job.companyName}「${job.title}」`,
    [job.location, job.direction || job.category].filter(Boolean).join(" / "),
    requirements.length ? `能力信号：${requirements.slice(0, 3).join(" / ")}` : "",
    job.salary.source === "official" ? "薪资来自官网公开样本" : "薪资为市场估算，需回官网核验",
    "完整岗位说明请打开官方链接",
  ].filter(Boolean);

  return {
    ...job,
    description: truncatePublicText(`岗位摘要：${summaryParts.join("；")}`, 280),
    requirements,
    tags: Array.from(new Set(job.tags.map(cleanText).filter(Boolean))).slice(0, 6),
    abilitySignals,
    evidenceSignals: (job.evidenceSignals ?? []).map((signal) => truncatePublicText(signal, 120)).slice(0, 5),
  };
}

function renderGeneratedModule(payload: JobPayload) {
  return `import type { Job } from "../types";

// Auto-generated by npm run scrape:jobs. Do not hand edit.
export const jobDataMeta = ${JSON.stringify(
    {
      generatedAt: payload.generatedAt,
      sources: payload.sources,
      careerSignalCoverage: payload.careerSignalCoverage,
    },
    null,
    2,
  )} as const;

export const jobs: Job[] = ${JSON.stringify(payload.jobs, null, 2)};
`;
}

function cleanText(value: unknown) {
  return typeof value === "string" ? value.replace(/\s+/g, " ").trim() : "";
}

function truncatePublicText(value: string, maxLength: number) {
  const text = cleanText(value);
  if (text.length <= maxLength) return text;
  return `${text.slice(0, Math.max(0, maxLength - 1)).trimEnd()}…`;
}

main();
